apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-05hq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-05hq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-05hq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-05hq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-05hq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jwto-tenant/rhtap-demo-app/hacbs-test-project-05hq@sha256:dab1c306681529d5d2ae2423430fe67063c79bff62dada6ce26fa5115d84bdbe
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
