apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-05hq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-jwto-tenant/rhtap-demo-app/hacbs-test-project-05hq@sha256:9ef29062b04b6c4ac69f11960ec857f9c195833ecc265f6daed5d2885d3d9cfa
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
